package com.multiteam.core.enums;

public enum RoleEnum {
  ROLE_OWNER,
  ROLE_ADMIN,
  ROLE_GUEST,

  ROLE_PROFESSIONAL,
  PERM_PROFESSIONAL_READ,

  ROLE_PATIENT,
  PERM_PATIENT_READ,
  PERM_PATIENT_WRITE,

  ROLE_SCHEDULE,
  PERM_SCHEDULE_READ,
  PERM_SCHEDULE_WRITE,

  PERM_TREATMENT_READ,
  PERM_TREATMENT_WRITE,

  PERM_ANAMNESE_READ,
  PERM_ANAMNESE_WRITE,

  PERM_DOCUMENT_READ,
  PERM_DOCUMENT_WRITE
}
