package com.multiteam.core.enums;

public enum RoleEnum {
    TENANT_ADMINISTRATOR_ID,
    ROLE_OWNER,
    ROLE_ADMIN,
    ROLE_PATIENT,
    ROLE_GUEST,
    ROLE_PROFESSIONAL,
    ROLE_SCHEDULE,
    PERM_TREATMENT_READ,
    PERM_TREATMENT_WRITE,
    PERM_PATIENT_READ,
    PERM_PATIENT_WRITE,
    PERM_SCHEDULE_READ,
    PERM_SCHEDULE_WRITE,
    PERM_USER_READ,
    PERM_USER_WRITE;
}
